name: Bot de Reservas UPB

on:
  schedule:
    # GitHub Actions usa la zona horaria UTC.
    # Las 00:01 UTC corresponden exactamente a las 20:01 en Bolivia.
    - cron: '1 0 * * *'
  workflow_dispatch: # Te agrega un botón en GitHub para ejecutarlo manualmente cuando quieras

jobs:
  ejecutar-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar entorno de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar Selenium
      run: pip install -r requirements.txt

    - name: Correr el script de reserva
      run: python reserva.py

    - name: Guardar captura de pantalla si hay un error
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-screenshot
        path: error_screenshot.png
