name: Bot de Reservas 4PM - 2AM

on:
  schedule:
    # TURNO 1: Inicia a las 16:00 de Bolivia (20:00 UTC)
    # Este bucle correrá por 6 horas (hasta las 22:00)
    - cron: '0 20 * * *'
    
    # TURNO 2: Inicia a las 22:00 de Bolivia (02:00 UTC del día siguiente)
    # Este bucle continuará desde las 22:00 hasta las 04:00 AM
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  ejecutar-bucle:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar entorno de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Correr el Bucle de Reservas
      run: python bucle.py

    - name: Guardar captura de pantalla del último error
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-screenshot-final
        path: error_screenshot.png
